### PR TITLE
plot: Do not draw marks outside axis intervals

### LINKED ISSUE #76: Plot marks do not respect axis bounds
Expected behaviour: Marks are drawn only for those points which are shown.

Observed: Marks are drawn even for those points which are outside of the axis min-max.

MRE:
```typ
#import "@preview/cetz:0.3.1"
#import "@preview/cetz-plot:0.1.0"

#set page(width: auto, height: auto)

#cetz.canvas({
  cetz-plot.plot.plot(
    size: (5,5),
    x-min: 1, x-max: 2,
    {
      cetz-plot.plot.add(
        domain: (0, 3),
        mark: "x",
        x=>x,
      )
    }
  )
})
```

image

I think the problem might be from here: 

https://github.com/cetz-package/cetz-plot/blob/master/src/plot/mark.typ#L37-L45

### PR DESCRIPTION
**Pull request by johannes-wolf**
Fixes #76

### CODE REVIEW

**Review by jamesrswift — APPROVED** [review]

**Comment by jamesrswift** [comment]
Tested this branch on what I was doing that highlighted the issue and it works now :)

**Comment by jamesrswift** [comment]
When axes are swapped, there's an issue with scaling it seems
```typ
#test-case({
  plot.plot(
    size: (10,6), 
    // y-max: 100,
    {
      plot.add(domain: (20, 30), x=>x, mark: "x", axes:("y", "x"))
    }
  )
})
```

image

**Comment by johannes-wolf** [comment]
> ```typst
> #test-case({
>   plot.plot(
>     size: (10,6), 
>     // y-max: 100,
>     {
>       plot.add(domain: (20, 30), x=>x, mark: "x", axes:("y", "x"))
>     }
>   )
> })
> ```

Good catch. Fixed.

**Review by jamesrswift — APPROVED** [review]

**Comment by johannes-wolf** [comment]
This PR introduces new problems, so I suggest closing this in favor of #81 which solves the problem in a better way.

**Pull request closed without merging**
